
package com.khveras.jaxws.baseObjects;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "timeTableService", targetNamespace = "http://www.khveras.com/TimeTableService", wsdlLocation = "file:/C:/Users/Andrei_Khveras/git/SOAP_TRAINING/JaxWsClient/src/main/resources/TimeTable.wsdl")
public class BaseTimeTableService
    extends Service
{

    private final static URL TIMETABLESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.khveras.jaxws.baseObjects.BaseTimeTableService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.khveras.jaxws.baseObjects.BaseTimeTableService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/Andrei_Khveras/git/SOAP_TRAINING/JaxWsClient/src/main/resources/TimeTable.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/Andrei_Khveras/git/SOAP_TRAINING/JaxWsClient/src/main/resources/TimeTable.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TIMETABLESERVICE_WSDL_LOCATION = url;
    }
    
    public BaseTimeTableService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }
    
//	private TimeTableService() {
//		super(TIMETABLESERVICE_WSDL_LOCATION, new QName("http://www.khveras.com/TimeTableService", "timeTableService"));
//	}


    /**
     * 
     * @return
     *     returns TimeTablePortType
     */
    @WebEndpoint(name = "timeTableService-soap11")
    public TimeTablePortType getTimeTableServiceSoap11() {
        return super.getPort(new QName("http://www.khveras.com/TimeTableService", "timeTableService-soap11"), TimeTablePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TimeTablePortType
     */
    @WebEndpoint(name = "timeTableService-soap11")
    public TimeTablePortType getTimeTableServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.khveras.com/TimeTableService", "timeTableService-soap11"), TimeTablePortType.class, features);
    }

}
