
package com.khveras.jaxws.baseObjects;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "timeTablePortType", targetNamespace = "http://www.khveras.com/TimeTableService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TimeTablePortType {


    /**
     * 
     * @param addTripInputPart
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.khveras.com/TimeTableService/addTrip")
    @WebResult(name = "operationResultResponse", targetNamespace = "http://www.khveras.com/TimeTableSchema", partName = "addTripOutputPart")
    public String addTrip(
        @WebParam(name = "addTripRequest", targetNamespace = "http://www.khveras.com/TimeTableSchema", partName = "addTripInputPart")
        Trip addTripInputPart);

    /**
     * 
     * @param editTrnDestInputPart
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.khveras.com/TimeTableService/editTrainDestination")
    @WebResult(name = "operationResultResponse", targetNamespace = "http://www.khveras.com/TimeTableSchema", partName = "editTrnDestinationOutputPart")
    public String editTrainDestination(
        @WebParam(name = "editTrnDestRequest", targetNamespace = "http://www.khveras.com/TimeTableSchema", partName = "editTrnDestInputPart")
        EditTrnDestRequest editTrnDestInputPart);

    /**
     * 
     * @param addBusInputPart
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.khveras.com/TimeTableService/addBus")
    @WebResult(name = "operationResultResponse", targetNamespace = "http://www.khveras.com/TimeTableSchema", partName = "addBusOutputPart")
    public String addBus(
        @WebParam(name = "addBusRequest", targetNamespace = "http://www.khveras.com/TimeTableSchema", partName = "addBusInputPart")
        Trip addBusInputPart);

    /**
     * 
     * @param deleteBusInputPart
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.khveras.com/TimeTableService/deleteBus")
    @WebResult(name = "operationResultResponse", targetNamespace = "http://www.khveras.com/TimeTableSchema", partName = "deleteBusOutputPart")
    public String deleteBus(
        @WebParam(name = "deleteBusRequest", targetNamespace = "http://www.khveras.com/TimeTableSchema", partName = "deleteBusInputPart")
        String deleteBusInputPart);

    /**
     * 
     * @param getTrnByDestInputPart
     * @return
     *     returns com.khveras.jaxws.client.Trip
     */
    @WebMethod(action = "http://www.khveras.com/TimeTableService/getTrainByDestination")
    @WebResult(name = "getTrnByDestResponse", targetNamespace = "http://www.khveras.com/TimeTableSchema", partName = "getTrnByDestOutputPart")
    public Trip getTrainListByDestination(
        @WebParam(name = "getTrnByDestRequest", targetNamespace = "http://www.khveras.com/TimeTableSchema", partName = "getTrnByDestInputPart")
        Station getTrnByDestInputPart);

}
